# Generated by Django 5.1.7 on 2025-05-22 12:27

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_created_alter_comment_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بایو')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[500, 500], upload_to='account_images/', verbose_name='تصویر')),
                ('job', models.CharField(blank=True, max_length=250, null=True, verbose_name='شغل')),
            ],
            options={
                'verbose_name': 'اکانت',
                'verbose_name_plural': 'اکانت ها',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویر ها'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('تکنولوژی', 'تکنولوی'), ('زبان برنامه نویسی', 'زبان برنامه نویسی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('بلاکچین', 'بلاکچین'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=1, verbose_name='زمان مطالعه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[600, 400], upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='پست'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='blog_image_created_1ba45b_idx'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
