# Generated by Django 5.1.7 on 2025-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_account_alter_image_options_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=1, verbose_name='زمان مطالعه'),
        ),
    ]
